config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/breeds', to: 'breeds#index'
  delete 'destroy-breed', to: 'breeds#destroy'

  get '/cats', to: 'cats#index'
  delete 'destroy-cat', to: 'cats#destroy'
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :cats, dependent: :destroy

  validates :remote_id, :name, :temperament,
            :origin, :description, :child_friendly,
            presence: true
  validates :remote_id, :name, uniqueness: true

  scope :by_name_search, -> (term) { where("name ILIKE ?", "%#{term}%") }
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :breed, counter_cache: true

  validates :remote_id, :url, :width, :height, presence: true
  validates :remote_id, :url, uniqueness: true

  paginates_per 10

  scope :by_breed_name, -> (breed_name) {
    joins(:breed).
    where(breed: { name: breed_name }).
    order(created_at: :desc).
    includes(:breed)
  }

  scope :by_newest, -> (page) {
    includes(:breed).
    order(created_at: :desc).
    page(page)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    if session[:user_id]
      @user ||= Admin.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  def index
    @breeds = if params[:search_term]
      Breed.by_name_search(params[:search_term])
    else
      Breed.order(:name)
    end
  end

  def destroy
    @breed = Breed.find(params[:id])
    @breed.destroy

    respond_to do |format|
      format.html { redirect_to breeds_path }
      format.turbo_stream
    end
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = if params[:breed_name]
      Cat.by_breed_name(params[:breed_name])
    else
      Cat.by_newest(params[:page])
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to cats_path }
      format.turbo_stream
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_to_cats_path, if: :logged_in?, only: :login

  def login
  end

  def create
    user = Admin.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to cats_path
    else
      render :login
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

  private

  def redirect_to_cats_path
    redirect_to cats_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/breeds/destroy.turbo_stream.erb
<%= turbo_stream.remove @breed %>

app/views/breeds/index.html.erb
<h1>Breeds#index</h1>

<%= form_tag(breeds_path, method: "get", id: "search-breed") do %>
  <%= label_tag(:search_term, "Search Breeds:") %>
  <%= text_field_tag(:search_term) %>
<% end %>

<% @breeds.each do |breed| %>
  <%= turbo_frame_tag dom_id(breed) do %>
    <h3>
      <%= breed.name %>
    </h3>
    <p>
    Cats of this breed: <%= breed.cats.size %>
    </p>
    <% if logged_in? %>
      <%= button_to "Destroy", destroy_breed_path(id: breed.id), method: :delete %>
    <% end %>
  <% end %>
<% end %>

app/views/cats/destroy.turbo_stream.erb
<%= turbo_stream.remove @cat %>

app/views/cats/index.html.erb
<h1>Cats#index</h1>

<%= turbo_frame_tag "cats_frame" do %>
  <% @cats.each do |cat| %>
    <%= turbo_frame_tag dom_id(cat) do %>
      <div>
        <p>
          <%= link_to cat.breed.name,
            cats_path(breed_name: cat.breed.name),
            data: { turbo_frame: "cats_frame" }
          %>
        </p>
        <%= image_tag cat.url, size: "180x250", id: cat.id %>

        <% if logged_in? %>
          <%= button_to "Destroy", destroy_cat_path(id: cat.id), method: :delete %>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheCatsShowcase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if logged_in? %>
      <%= button_to "Logout", logout_path, method: :delete %>
    <% end %>

    <%= yield %>
  </body>
</html>